[package]
name = "Tournament"
version = "0.0.1"

[dependencies]
AptosFramework = { local = "../../../../../aptos-move/framework/aptos-framework" }
AptosTokenObjects = { local = "../../../../../aptos-move/framework/aptos-token-objects" }
MoveStdlib = { local = "../../../../../aptos-move/framework/move-stdlib" }
AptosToken = { local = "../../../../../aptos-move/framework/aptos-token" }

[addresses]
tournament = "0xCAFE"
